version: '3.8'

services:
  web:
    image: wvxbs/curriculum:prod
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production,
      REACT_ENV: production,
    ports:
      - 8080:8080
