version: '3.4'

services:
  web:
    image: wvxbs/curriculum:prod
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production,
      REACT_ENV: production
      REACT_APP_BASE_PATH: $REACT_APP_BASE_PATH
    ports:
      - 3000:3000

  api:
    image: wvxbs/curriculum-rest:latest
    ports:
      - 3001:3001