version: '3.4'

services:
  curriculum:
    image: curriculum
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      API_URL: ${URL}
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
