version: '3.8'

services:
  web:
    image: wvxbs/curriculum:dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development,
      REACT_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/app/dev

  api:
    image: wvxbs/curriculum-rest
    ports:
      - 3001:3001
