version: '3.8'

services:
  web:
    image: wvxbs/curriculum
    build: .
    environment:
      NODE_ENV: development,
      REACT_ENV: development,
      API_URL: ${API_URL} 
    ports:
      - 3000:3000
    volumes:
      - .:/app
